/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Ries
 */
public class FocusPanel extends javax.swing.JPanel {

    /**
     * Creates new form FocusPanel
     */
    public FocusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_controls = new javax.swing.JPanel();
        jTextField_position = new javax.swing.JTextField();
        jToggleButton_lockz = new javax.swing.JToggleButton();
        jToggleButton_monitorZ = new javax.swing.JToggleButton();
        jLabel_position = new javax.swing.JLabel();
        jToggleButton_set0 = new javax.swing.JToggleButton();
        jTextField_0position = new javax.swing.JTextField();
        jPanel_graph = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Focus"));
        setMaximumSize(new java.awt.Dimension(462, 168));
        setMinimumSize(new java.awt.Dimension(462, 168));
        setPreferredSize(new java.awt.Dimension(462, 168));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTextField_position.setText("0");

        jToggleButton_lockz.setText("Lock");
        jToggleButton_lockz.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton_lockz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_lockzActionPerformed(evt);
            }
        });

        jToggleButton_monitorZ.setText("Monitor");
        jToggleButton_monitorZ.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton_monitorZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_monitorZActionPerformed(evt);
            }
        });

        jLabel_position.setText("Position:");

        jToggleButton_set0.setText("Set 0");
        jToggleButton_set0.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton_set0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_set0ActionPerformed(evt);
            }
        });

        jTextField_0position.setText("0");

        javax.swing.GroupLayout jPanel_controlsLayout = new javax.swing.GroupLayout(jPanel_controls);
        jPanel_controls.setLayout(jPanel_controlsLayout);
        jPanel_controlsLayout.setHorizontalGroup(
            jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_controlsLayout.createSequentialGroup()
                        .addGroup(jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jToggleButton_lockz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton_monitorZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_position, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_position, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_controlsLayout.createSequentialGroup()
                        .addGroup(jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_0position, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_set0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        jPanel_controlsLayout.setVerticalGroup(
            jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_controlsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_position)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton_set0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_0position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton_monitorZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton_lockz)
                .addGap(36, 36, 36))
        );

        add(jPanel_controls);

        javax.swing.GroupLayout jPanel_graphLayout = new javax.swing.GroupLayout(jPanel_graph);
        jPanel_graph.setLayout(jPanel_graphLayout);
        jPanel_graphLayout.setHorizontalGroup(
            jPanel_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        jPanel_graphLayout.setVerticalGroup(
            jPanel_graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        add(jPanel_graph);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_lockzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_lockzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_lockzActionPerformed

    private void jToggleButton_monitorZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_monitorZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_monitorZActionPerformed

    private void jToggleButton_set0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_set0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_set0ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_position;
    private javax.swing.JPanel jPanel_controls;
    private javax.swing.JPanel jPanel_graph;
    private javax.swing.JTextField jTextField_0position;
    private javax.swing.JTextField jTextField_position;
    private javax.swing.JToggleButton jToggleButton_lockz;
    private javax.swing.JToggleButton jToggleButton_monitorZ;
    private javax.swing.JToggleButton jToggleButton_set0;
    // End of variables declaration//GEN-END:variables
}
