/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Ries
 */
public class LaserParamTab extends javax.swing.JPanel {

    /**
     * Creates new form LaserParamTab
     */
    public LaserParamTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singleLaserParamPanel1 = new gui.SingleLaserParamPanel();
        singleLaserParamPanel2 = new gui.SingleLaserParamPanel();
        singleLaserParamPanel3 = new gui.SingleLaserParamPanel();
        singleLaserParamPanel4 = new gui.SingleLaserParamPanel();

        setLayout(new java.awt.GridLayout(2, 2));
        add(singleLaserParamPanel1);
        add(singleLaserParamPanel2);
        add(singleLaserParamPanel3);
        add(singleLaserParamPanel4);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.SingleLaserParamPanel singleLaserParamPanel1;
    private gui.SingleLaserParamPanel singleLaserParamPanel2;
    private gui.SingleLaserParamPanel singleLaserParamPanel3;
    private gui.SingleLaserParamPanel singleLaserParamPanel4;
    // End of variables declaration//GEN-END:variables
}
