/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Ries
 */
public class LaserPanel extends javax.swing.JPanel {

    /**
     * Creates new form LaserPanel
     */
    public LaserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laserControl1 = new gui.LaserControl();
        laserControl2 = new gui.LaserControl();
        laserControl3 = new gui.LaserControl();
        laserControl4 = new gui.LaserControl();

        setLayout(new java.awt.GridBagLayout());
        add(laserControl1, new java.awt.GridBagConstraints());
        add(laserControl2, new java.awt.GridBagConstraints());
        add(laserControl3, new java.awt.GridBagConstraints());
        add(laserControl4, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.LaserControl laserControl1;
    private gui.LaserControl laserControl2;
    private gui.LaserControl laserControl3;
    private gui.LaserControl laserControl4;
    // End of variables declaration//GEN-END:variables
}
