package swing;


public class FiltersPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterPanel
     */
    public FiltersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToggleButton_filter1 = new javax.swing.JToggleButton();
        jToggleButton_filter2 = new javax.swing.JToggleButton();
        jToggleButton_filter3 = new javax.swing.JToggleButton();
        jToggleButton_filter4 = new javax.swing.JToggleButton();
        jToggleButton_filter6 = new javax.swing.JToggleButton();
        jToggleButton_filter5 = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Filters"));

        jToggleButton_filter1.setText("Sp");
        jToggleButton_filter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter1ActionPerformed(evt);
            }
        });

        jToggleButton_filter2.setText("525/50");
        jToggleButton_filter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter2ActionPerformed(evt);
            }
        });

        jToggleButton_filter3.setText("600/60");
        jToggleButton_filter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter3ActionPerformed(evt);
            }
        });

        jToggleButton_filter4.setText("700/100");
        jToggleButton_filter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter4ActionPerformed(evt);
            }
        });

        jToggleButton_filter6.setText("Empty");
        jToggleButton_filter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter6ActionPerformed(evt);
            }
        });

        jToggleButton_filter5.setText("Empty");
        jToggleButton_filter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_filter5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton_filter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton_filter5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton_filter2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_filter6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jToggleButton_filter3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jToggleButton_filter4)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_filter1)
                    .addComponent(jToggleButton_filter2)
                    .addComponent(jToggleButton_filter3)
                    .addComponent(jToggleButton_filter4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton_filter5)
                    .addComponent(jToggleButton_filter6)))
        );
    }// </editor-fold>                        

    private void jToggleButton_filter1ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jToggleButton_filter2ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jToggleButton_filter3ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jToggleButton_filter4ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jToggleButton_filter5ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jToggleButton_filter6ActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton jToggleButton_filter1;
    private javax.swing.JToggleButton jToggleButton_filter2;
    private javax.swing.JToggleButton jToggleButton_filter3;
    private javax.swing.JToggleButton jToggleButton_filter4;
    private javax.swing.JToggleButton jToggleButton_filter5;
    private javax.swing.JToggleButton jToggleButton_filter6;
    // End of variables declaration                   
}

