/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import device.MSystem;
import micromanager.Configuration;

/**
 *
 * @author Ries
 */
public class LaserParamTab extends javax.swing.JPanel {

	MSystem sys_;

    public LaserParamTab(MSystem sys) {
    	sys_ = sys;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singleLaserParamPanel3 = new SingleLaserParam(sys_,Configuration.laserkeys[3],300, true,Configuration.green);
        singleLaserParamPanel2 = new SingleLaserParam(sys_,Configuration.laserkeys[1],100, false,Configuration.blue);
        singleLaserParamPanel4 = new SingleLaserParam(sys_,Configuration.laserkeys[2],100, false,Configuration.red);
        singleLaserParamPanel1 = new SingleLaserParam(sys_,Configuration.laserkeys[0],100, false,Configuration.uv);

        setLayout(new java.awt.GridLayout(2, 2));
        add(singleLaserParamPanel1);
        add(singleLaserParamPanel2);
        add(singleLaserParamPanel3);
        add(singleLaserParamPanel4);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SingleLaserParam singleLaserParamPanel1;
    private SingleLaserParam singleLaserParamPanel2;
    private SingleLaserParam singleLaserParamPanel3;
    private SingleLaserParam singleLaserParamPanel4;
    // End of variables declaration//GEN-END:variables
}
