/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import threader.Threader;
import device.MSystem;

/**
 *
 * @author Ries
 */
public class Tabs extends javax.swing.JPanel {

	MSystem sys_;
	Threader th_;
	
    public Tabs(MSystem sys, Threader th) {
    	sys_ = sys;
    	th_ = th;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_QPD = new javax.swing.JTabbedPane();
        qPDPanel = new QPDPanel(sys_,th_);
        activationPanel = new ActivationPanel(sys_,th_);
        laserParamTab = new LaserParamTab(sys_);
        controlPanel = new ControlPanel(sys_);

        setMaximumSize(new java.awt.Dimension(462, 240));
        setMinimumSize(new java.awt.Dimension(440, 240));
        setPreferredSize(new java.awt.Dimension(462, 240));

        jTabbedPane_QPD.addTab("QPD", qPDPanel);
        jTabbedPane_QPD.addTab("Activation", activationPanel);
        jTabbedPane_QPD.addTab("Lasers", laserParamTab);

        controlPanel.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane_QPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane_QPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public ActivationPanel activationPanel;
    private ControlPanel controlPanel;
    private javax.swing.JTabbedPane jTabbedPane_QPD;
    private LaserParamTab laserParamTab;
    public QPDPanel qPDPanel;
    // End of variables declaration//GEN-END:variables
}
